apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-blue-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-blue-green
  template:
    metadata:
      labels:
        app: flask-blue-green
    spec:
      containers:
      - name: flask-container
        image: ganesh243/flask-app:1.0.0 # This is your initial version
        ports:
        - containerPort: 5000
