apiVersion: v1
kind: Service
metadata:
  name: flask-primary-svc
  annotations:
    harness.io/primary-service: "true"
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-blue-green
---
apiVersion: v1
kind: Service
metadata:
  name: flask-stage-svc
  annotations:
    harness.io/stage-service: "true"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: flask-blue-green
